name = "L38K"
id = "l38k"

# Tables
[[table]]
    id = 0
    offset = 0x836C

[[table]]
    id = 1
    offset = 0x9AE4

[[table]]
    id = 2
    offset = 0x1CE84

[[table]]
    id = 3
    offset = 0x1FE54

[[table]]
    id = 4
    offset = 0x9BD0

# Axes
[[axis]]
    id = "rpm_500"
    offset = 0

# Checksums
[[checksum]]
    mode = "basic"
    offset = 0x48000
    size = 0xB8000
    target = 0x5AA55AA5

    [[checksum.modify]]
        offset = 0
        size = 4

# Identifiers
[[identifiers]]
    offset = 0x2A7C8
    data = "L38K"
    name = "Some Timing Table"
    description = "Unknown"
    datatype = "float"
    
